from __future__ import annotations

import torch
from torch import nn
from torch.nn import functional as F


class ConvReLU(nn.Sequential):
    def __init__(self, channels: int) -> None:
        super().__init__(nn.Conv2d(channels, channels, 3, padding=1, bias=False), nn.ReLU(inplace=True))


class SpatialAttention(nn.Module):
    """Max/average channel pooling attention map from Equation (23)."""

    def __init__(self) -> None:
        super().__init__()
        # TODO: Not explicitly specified in the paper
        self.conv = nn.Conv2d(2, 1, kernel_size=7, padding=3, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        max_pool = x.amax(dim=1, keepdim=True)
        avg_pool = x.mean(dim=1, keepdim=True)
        return torch.sigmoid(self.conv(torch.cat((max_pool, avg_pool), dim=1)))


class CrossAttentionBlock(nn.Module):
    """One bidirectional cross-attention and dual ConvReLU block, (23)-(24)."""

    def __init__(self, channels: int) -> None:
        super().__init__()
        self.sp_attention = SpatialAttention()
        self.pixel_attention = SpatialAttention()
        self.sp_conv1 = ConvReLU(channels)
        self.sp_conv2 = ConvReLU(channels)
        self.pixel_conv1 = ConvReLU(channels)
        self.pixel_conv2 = ConvReLU(channels)

    def forward(self, pixel: torch.Tensor, superpixel: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """Fuse two ``[B,C,H,W]`` branches and return tensors of the same shapes."""
        attention_sp = self.sp_attention(superpixel)
        attention_pixel = self.pixel_attention(pixel)
        # Equation (23) applies the attention generated by one stream to the
        # other, giving bidirectional cross-wise information flow.
        # Equation (23): A_SP is generated from F_SP and applied to F, while A
        # is generated from F and applied to F_SP.
        attended_superpixel = attention_sp * pixel
        attended_pixel = attention_pixel * superpixel
        superpixel = self.sp_conv2(self.sp_conv1(attended_superpixel)) + superpixel
        pixel = self.pixel_conv2(self.pixel_conv1(attended_pixel)) + pixel
        return pixel, superpixel


class CrossAttentionCollaborativeNetwork(nn.Module):
    """CACN with the paper-specified five serial cross-attention blocks."""

    def __init__(self, channels: int, num_blocks: int = 5) -> None:
        super().__init__()
        if num_blocks != 5:
            raise ValueError("The manuscript explicitly sets the CACN block count to five")
        self.blocks = nn.ModuleList([CrossAttentionBlock(channels) for _ in range(num_blocks)])

    def forward(self, pixel: torch.Tensor, superpixel: torch.Tensor) -> torch.Tensor:
        """Return ``F_CACN`` with shape ``[B,2C,H,W]``."""
        if pixel.shape != superpixel.shape:
            superpixel = F.interpolate(superpixel, size=pixel.shape[-2:], mode="bilinear", align_corners=False)
        for block in self.blocks:
            pixel, superpixel = block(pixel, superpixel)
        return torch.cat((pixel, superpixel), dim=1)
